name: functional_collections
version: 0.1.1
author: svarzee <svarzee@gmail.com>
homepage: https://github.com/svarzee/functional_collections
description: >-
  Functional collections.
environment:
  sdk: '>=2.3.0 <3.0.0'

dev_dependencies:
  test: ^1.6.0
  benchmark_harness: ^1.0.5