name: functional_collections
version: 0.1.8
author: svarzee <svarzee@gmail.com>
homepage: https://github.com/svarzee/functional_collections
description: >-
  Functional collections are immutable, adding or removing items efficiently creates a new collection. You can choose from: `FOption`, `FList`, `FSet`, `FMap`, `FTuple`.
environment:
  sdk: '>=2.3.0 <3.0.0'

dev_dependencies:
  test: ^1.6.0
  benchmark_harness: ^1.0.5